// birds.js
const birdsData = [
    {
        id: 1,
        common_name: "Snow goose",
        scientific_name: "Anser caerulescens",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Snow_goose_in_Central_Park_%2833138%29.jpg/500px-Snow_goose_in_Central_Park_%2833138%29.jpg"
    },
    {
        id: 2,
        common_name: "Ross's goose",
        scientific_name: "Anser rossii",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Ross%27s_Goose_%28Chen_rossii%29_%2823321411711%29.jpg/500px-Ross%27s_Goose_%28Chen_rossii%29_%2823321411711%29.jpg"
    },
    {
        id: 3,
        common_name: "Greater white-fronted goose",
        scientific_name: "Anser albifrons",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Greater_white-fronted_goose_in_flight-1045.jpg/500px-Greater_white-fronted_goose_in_flight-1045.jpg"
    },
    {
        id: 4,
        common_name: "Brant",
        scientific_name: "Branta bernicla",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Atlantic_Brant_Fly-By_Wiki.png/500px-Atlantic_Brant_Fly-By_Wiki.png"
    },
    {
        id: 5,
        common_name: "Cackling goose",
        scientific_name: "Branta hutchinsii",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: "https://upload.wikimedia.org/wikipedia/commons/b/b4/AleutianCanadaGoose2.jpg"
    },
    {
        id: 6,
        common_name: "Canada goose",
        scientific_name: "Branta canadensis",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 7,
        common_name: "Mute swan",
        scientific_name: "Cygnus olor",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 8,
        common_name: "Trumpeter swan",
        scientific_name: "Cygnus buccinator",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 9,
        common_name: "Tundra swan",
        scientific_name: "Cygnus columbianus",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 10,
        common_name: "Wood duck",
        scientific_name: "Aix sponsa",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 11,
        common_name: "Garganey",
        scientific_name: "Spatula querquedula",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 12,
        common_name: "Blue-winged teal",
        scientific_name: "Spatula discors",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 13,
        common_name: "Cinnamon teal",
        scientific_name: "Spatula cyanoptera",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 14,
        common_name: "Northern shoveler",
        scientific_name: "Spatula clypeata",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 15,
        common_name: "Gadwall",
        scientific_name: "Mareca strepera",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 16,
        common_name: "Eurasian wigeon",
        scientific_name: "Mareca penelope",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 17,
        common_name: "American wigeon",
        scientific_name: "Mareca americana",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 18,
        common_name: "Mallard",
        scientific_name: "Anas fulvigula",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 19,
        common_name: "American black duck",
        scientific_name: "Anas rubripes",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 20,
        common_name: "Northern pintail",
        scientific_name: "Anas bahamensis",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 21,
        common_name: "Green-winged teal",
        scientific_name: "Anas crecca",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 22,
        common_name: "Canvasback",
        scientific_name: "Aythya valisineria",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 23,
        common_name: "Redhead",
        scientific_name: "Aythya americana",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 24,
        common_name: "Ring-necked duck",
        scientific_name: "Aythya collaris",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 25,
        common_name: "Tufted duck",
        scientific_name: "Aythya fuligula",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 26,
        common_name: "Greater scaup",
        scientific_name: "Aythya marila",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 27,
        common_name: "Lesser scaup",
        scientific_name: "Aythya affinis",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 28,
        common_name: "King eider",
        scientific_name: "Somateria spectabilis",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 29,
        common_name: "Common eider",
        scientific_name: "Somateria mollissima",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 30,
        common_name: "Harlequin duck",
        scientific_name: "Histrionicus histrionicus",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 31,
        common_name: "Surf scoter",
        scientific_name: "Melanitta perspicillata",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 32,
        common_name: "White-winged scoter",
        scientific_name: "Melanitta deglandi",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 33,
        common_name: "Black scoter",
        scientific_name: "Melanitta americana",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 34,
        common_name: "Long-tailed duck",
        scientific_name: "Clangula hyemalis",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 35,
        common_name: "Bufflehead",
        scientific_name: "Bucephala albeola",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 36,
        common_name: "Common goldeneye",
        scientific_name: "Bucephala clangula",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 37,
        common_name: "Barrow's goldeneye",
        scientific_name: "Bucephala islandica",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 38,
        common_name: "Hooded merganser",
        scientific_name: "Lophodytes cucullatus",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 39,
        common_name: "Common merganser",
        scientific_name: "Mergus merganser",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 40,
        common_name: "Red-breasted merganser",
        scientific_name: "Mergus serrator",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 41,
        common_name: "Ruddy duck",
        scientific_name: "Oxyura jamaicensis",
        type: "Ducks, geese, and waterfowl",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 42,
        common_name: "Wild turkey",
        scientific_name: "Meleagris gallopavo",
        type: "Pheasants, grouse, and allies",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 43,
        common_name: "Ruffed grouse",
        scientific_name: "Bonasa umbellus",
        type: "Pheasants, grouse, and allies",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 44,
        common_name: "Spruce grouse",
        scientific_name: "Canachites canadensis",
        type: "Pheasants, grouse, and allies",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 45,
        common_name: "Willow ptarmigan",
        scientific_name: "Lagopus lagopus",
        type: "Pheasants, grouse, and allies",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 46,
        common_name: "Rock ptarmigan",
        scientific_name: "Lagopus muta",
        type: "Pheasants, grouse, and allies",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 47,
        common_name: "Sharp-tailed grouse",
        scientific_name: "Tympanuchus phasianellus",
        type: "Pheasants, grouse, and allies",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 48,
        common_name: "Greater prairie-chicken",
        scientific_name: "Tympanuchus cupido",
        type: "Pheasants, grouse, and allies",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 49,
        common_name: "Grey partridge",
        scientific_name: "Perdix perdix",
        type: "Pheasants, grouse, and allies",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    },
    {
        id: 50,
        common_name: "Ring-necked pheasant",
        scientific_name: "Phasianus colchicus",
        type: "Pheasants, grouse, and allies",
        season: null,
        height_cm: null,
        wingspan_cm: null,
        fact: null,
        image: null
    }
];
